
swagger: "2.0"
info:
  title: URL Shorten
  description: API to short given URLS;
  version: "1.0.0"
host: localhost:8080
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /shorten:
    post:
      summary: Shorten the given URL
      description: Create an shorten URL based on the given URL
      parameters:
        - in: body
          name: url
          description: URL to be shortened
          required: true
          schema:
            type: object
            properties:
              url:
                type: string
      responses:
        200:
          description: URL shortened with success
          schema:
            type: object
            properties:
              shortenedUrl:
                type: string
        400:
          description: Bad Parameter
        500:
          description: Server Error
  /{shortenedUrl}:
    get:
      summary: Redirect to the shortened URL
      description: Given the shortened URL redirect to the relative URL
      parameters:
        - in: path
          name: shortenedUrl
          description: Shortened URL relative to wanted URL
          required: true
          schema:
            type: string
      responses:
        301:
          description: Redirect to the relative URL
        404:
          description: Shortened URL not found
        500:
          description: Server Error